<?php

declare(strict_types=1);

namespace Soviann\DeployTasksBundle\Command;

use Soviann\DeployTasksBundle\Helper\HostRunnerConfig;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Filesystem\Filesystem;

/** @internal */
#[AsCommand(
    name: 'deploytasks:host:config',
    description: 'Render (or write) the host runner env config matching soviann_deploy_tasks.host.*.',
)]
final class DeployTasksHostConfigCommand extends Command
{
    public function __construct(
        /** Directory scanned for host-scope `*.sh` tasks (the host.directory bundle config). */
        private readonly string $hostTasksDir,
        /** Host runner's append-only completion log (the host.log_path bundle config). */
        private readonly string $hostLogPath,
        /** Host runner's flock file (the host.lock_path bundle config). */
        private readonly string $hostLockPath,
        private readonly ?string $projectDir = null,
    ) {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this
            ->addOption(
                'write',
                null,
                InputOption::VALUE_NONE,
                'Write the exports to deploy-tasks-host.local.sh (sourced by bin/deploy-tasks-host.sh) instead of printing them.',
            )
            ->setHelp(<<<'EOT'
                The <info>%command.name%</info> command renders the <comment>DEPLOY_TASKS_HOST_*</comment> environment
                exports that make <info>bin/deploy-tasks-host.sh</info> use the same host-task directory,
                completion log, and lock file as the bundle's PHP-side commands
                (<info>deploytasks:status</info>, <info>deploytasks:skip:host</info>, …):

                    <info>%command.full_name%</info>

                Paths under the project directory are emitted project-relative — the runner
                resolves them against the project root, so they stay correct even when the
                PHP container mounts the project at a different absolute path than the host.

                With <comment>--write</comment>, the exports go to <comment>deploy-tasks-host.local.sh</comment> at the
                project root, which the runner sources on every run:

                    <info>%command.full_name% --write</info>

                Re-run it after changing any <comment>soviann_deploy_tasks.host.*</comment> value;
                <info>deploytasks:status</info> warns when the written file has drifted from the config.
                EOT)
        ;
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);

        $values = HostRunnerConfig::envValues($this->hostTasksDir, $this->hostLogPath, $this->hostLockPath, $this->projectDir);

        foreach ($values as $envVar => $value) {
            if (\str_contains($value, "'") || \str_contains($value, "\n")) {
                $io->error(\sprintf('%s value "%s" cannot be represented as a single-quoted shell literal.', $envVar, $value));

                return Command::FAILURE;
            }

            if (\str_starts_with($value, '/')) {
                $io->warning(\sprintf('%s is outside the project directory (%s) — make sure this absolute path is valid on the host, not only inside the PHP container.', $envVar, $value));
            }
        }

        $lines = [HostRunnerConfig::GENERATED_MARKER.' — regenerate after changing soviann_deploy_tasks.host.*'];

        foreach ($values as $envVar => $value) {
            $lines[] = \sprintf("export %s='%s'", $envVar, $value);
        }

        if (!(bool) $input->getOption('write')) {
            $output->writeln($lines);

            return Command::SUCCESS;
        }

        if (null === $this->projectDir) {
            $io->error('Cannot locate the project directory to write deploy-tasks-host.local.sh.');

            return Command::FAILURE;
        }

        $path = $this->projectDir.'/'.HostRunnerConfig::LOCAL_SH_BASENAME;

        if (\is_file($path) && !\str_contains((string) \file_get_contents($path), HostRunnerConfig::GENERATED_MARKER)) {
            $io->error(\sprintf('"%s" exists and was not generated by this command — merge these exports into it manually:', $path));
            $output->writeln($lines);

            return Command::FAILURE;
        }

        (new Filesystem())->dumpFile($path, \implode("\n", $lines)."\n");

        $io->success(\sprintf('Wrote %s — bin/deploy-tasks-host.sh sources it on every run.', $path));

        return Command::SUCCESS;
    }
}
