<?php

declare(strict_types=1);

namespace Soviann\DeployTasksBundle\Helper;

/**
 * Translates the bundle's host.* config into the runner's DEPLOY_TASKS_HOST_*
 * env values, and reads back a deploy-tasks-host.local.sh previously generated
 * by deploytasks:host:config — the two halves of the verifiable coupling
 * between the PHP ops plane and bin/deploy-tasks-host.sh.
 *
 * @internal
 */
final class HostRunnerConfig
{
    /** File the runner sources on every run (project root). */
    public const LOCAL_SH_BASENAME = 'deploy-tasks-host.local.sh';

    /** First-line marker identifying files this bundle generated (hand-written files are never validated or overwritten). */
    public const GENERATED_MARKER = '# Generated by deploytasks:host:config';

    /** Bundle host.* config key => runner env var. */
    public const ENV_VARS = [
        'directory' => 'DEPLOY_TASKS_HOST_DIR',
        'log_path' => 'DEPLOY_TASKS_HOST_STORAGE',
        'lock_path' => 'DEPLOY_TASKS_HOST_LOCK',
    ];

    /**
     * Converts a configured (container-side) path into the value the host
     * runner needs: project-relative when under the project dir — the runner
     * cds to the project root, so relative paths stay correct even when the
     * PHP container mounts the project at a different absolute path than the
     * host — absolute (verbatim) otherwise.
     */
    public static function runnerPath(string $configuredPath, ?string $projectDir): string
    {
        $normalized = PathNormalizer::normalize($configuredPath);

        if (null === $projectDir) {
            return $normalized;
        }

        $base = \rtrim(PathNormalizer::normalize($projectDir), '/').'/';

        return \str_starts_with($normalized, $base) ? \substr($normalized, \strlen($base)) : $normalized;
    }

    /**
     * Parses the exports of a deploy-tasks-host.local.sh generated by
     * deploytasks:host:config. Returns null when the file is absent or not
     * ours (no marker).
     *
     * @return array<string, string>|null env var name => value
     */
    public static function readGeneratedLocalSh(string $path): ?array
    {
        if (!\is_file($path)) {
            return null;
        }

        $contents = \file_get_contents($path);

        if (false === $contents || !\str_contains($contents, self::GENERATED_MARKER)) {
            return null;
        }

        $values = [];

        foreach (self::ENV_VARS as $envVar) {
            if (1 === \preg_match('/^export '.$envVar."='([^']*)'$/m", $contents, $matches)) {
                $values[$envVar] = $matches[1];
            }
        }

        return $values;
    }
}
